#!/bin/bash
fun_prog ()
{
    comando[0]="$1" 
    ${comando[0]}  > /dev/null 2>&1 & 
    tput civis
    echo -ne "\033[1;32m.\033[1;33m.\033[1;31m. \033[1;32m"
    while [ -d /proc/$! ]
    do
        for i in / - \\ \|
        do
            sleep .1
            echo -ne "\e[1D$i"
        done
    done
    tput cnorm
    echo -e "\e[1DOK"
}
if [[ "$(grep -c "Ubuntu" /etc/issue.net)" = "1" ]]; then
system=$(cut -d' ' -f1 /etc/issue.net)
system+=$(echo ' ')
system+=$(cut -d' ' -f2 /etc/issue.net |awk -F "." '{print $1}')
elif [[ "$(grep -c "Debian" /etc/issue.net)" = "1" ]]; then
system=$(cut -d' ' -f1 /etc/issue.net)
system+=$(echo ' ')
system+=$(cut -d' ' -f3 /etc/issue.net)
else
system=$(cut -d' ' -f1 /etc/issue.net)
fi
_ons=$(ps -x | grep sshd | grep -v root | grep priv | wc -l)
_ram=$(printf ' %-9s' "$(free -h | grep -i mem | awk {'print $2'})")
_usor=$(printf '%-8s' "$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')")
_usop=$(printf '%-5s' "$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')")
_core=$(printf '%-5s' "$(grep -c cpu[0-9] /proc/stat)")
_system=$(printf '%-14s' "$system")
_hora=$(printf '%(%H:%M:%S)T')
fun_update () {
    apt-get update -y > /dev/null 2>&1
}

fun_upgrade () {
    apt-get upgrade -y > /dev/null 2>&1
}
fun_atpweb () {
    rm /bin/pweb > /dev/null 2>&1
    sleep 5
    cd /bin || exit
    wget https://github.com/JeanRocha91x/psshplus-/raw/main/gestorssh/pweb > /dev/null 2>&1
    chmod 777 pweb > /dev/null 2>&1
    clear
    mkdir /bin/ppweb > /dev/null 2>&1
cd /bin/ppweb || exit
rm *.sh > /dev/null 2>&1
wget https://github.com/JeanRocha91x/psshplus-/raw/main/gestorssh/install.sh > /dev/null 2>&1
wget https://github.com/JeanRocha91x/psshplus-/raw/main/gestorssh/ubuinst.sh > /dev/null 2>&1
wget https://github.com/JeanRocha91x/psshplus-/raw/main/gestorssh/senharoot.sh > /dev/null 2>&1
wget https://github.com/JeanRocha91x/psshplus-/raw/main/gestorssh/restbanco.sh > /dev/null 2>&1
wget https://github.com/JeanRocha91x/psshplus-/raw/main/gestorssh/restbanco18.sh > /dev/null 2>&1
wget https://github.com/JeanRocha91x/psshplus-/raw/main/gestorssh/empresa.sh > /dev/null 2>&1
wget https://github.com/JeanRocha91x/psshplus-/raw/main/gestorssh/updatepainel.sh > /dev/null 2>&1
wget https://github.com/JeanRocha91x/psshplus-/raw/main/gestorssh/updatepainel18.sh > /dev/null 2>&1
wget https://github.com/JeanRocha91x/psshplus-/raw/main/gestorssh/updatepainelarm.sh > /dev/null 2>&1
wget https://github.com/JeanRocha91x/psshplus-/raw/main/gestorssh/updatepainelarm18.sh > /dev/null 2>&1
chmod 777 *.sh > /dev/null 2>&1
clear
}

fun_limpiarepositorios () {
##LIMPA ROOT
rm -rf /root/*.sh* > /dev/null 2>&1
##LIMPA HTML
rm -rf /var/www/html
[[ ! -d /var ]] && mkdir /var
[[ ! -d /var/www ]] && mkdir /var/www
[[ ! -d /var/www/html ]] && mkdir /var/www/html
}

##INSTALAR PAINEL
painel_inst () {
echo ""
echo ""  
echo -e "\033[1;36mSELECIONE O SISTEMA DE SUA VPS: \033[1;37m"
echo ""
echo -e "[1] - UBUNTU 18"
echo ""
echo -e "[2] - DEBIAN 8 OU UBUNTU 14"
echo ""
echo -ne "\033[1;36mOpção: \033[1;37m"
read resposta
if [[ "$resposta" = '1' ]]; then
    /bin/ppweb/ubuinst.sh
elif [[ "$resposta" = '2' ]]; then
/bin/ppweb/install.sh
    else
 echo ""
    echo -e "\033[1;31mOpção inválida !\033[0m"
    sleep 1
    pweb
fi
}
painel_att () {
    echo ""
echo ""
echo -e "\033[1;36mSELECIONE QUAL SISTEMA QUE QUER ATUALIZAR: \033[1;37m"
echo ""
echo -e "[1] - PAINEL WEB NO UBUNTU 18"
echo ""
echo -e "[2] - PAINEL WEB NO DEBIAN 8 OU UBUNTU 14"
echo ""
echo -ne "\033[1;36mOpção: \033[1;37m"
read resposta
if [[ "$resposta" = '1' ]]; then
    painel_att18
elif [[ "$resposta" = '2' ]]; then
painel_att14
    else
 echo ""
    echo -e "\033[1;31mOpção inválida !\033[0m"
    sleep 1
    pweb
fi
}
painel_att18 () {
    echo ""
echo ""
echo -e "\033[1;36mSELECIONE O MODO COMPATÍVEL CONFORME SUA VPS SSH: \033[1;37m"
echo ""
echo -e "[1] - VPS SSH PADRÃO X86_64"
echo ""
echo -e "[2] - VPS SSH NA AMPERE ARM"
echo ""
echo -ne "\033[1;36mOpção: \033[1;37m"
read resposta
if [[ "$resposta" = '1' ]]; then
    /bin/ppweb/updatepainel18.sh
elif [[ "$resposta" = '2' ]]; then
/bin/ppweb/updatepainelarm18.sh
    else
 echo ""
    echo -e "\033[1;31mOpção inválida !\033[0m"
    sleep 1
    pweb
fi
}
painel_att14 () {
    echo ""
echo ""
echo -e "\033[1;36mSELECIONE O MODO COMPATÍVEL CONFORME SUA VPS SSH: \033[1;37m"
echo ""
echo -e "[1] - VPS SSH PADRÃO X86_64"
echo ""
echo -e "[2] - VPS SSH NA AMPERE ARM"
echo ""
echo -ne "\033[1;36mOpção: \033[1;37m"
read resposta
if [[ "$resposta" = '1' ]]; then
    /bin/ppweb/updatepainel.sh
elif [[ "$resposta" = '2' ]]; then
/bin/ppweb/updatepainelarm.sh
    else
 echo ""
    echo -e "\033[1;31mOpção inválida !\033[0m"
    sleep 1
    pweb
fi
}
painel_rest () {
echo ""
echo ""
echo -e "\033[1;36mSELECIONE QUAL SISTEMA QUE QUER RESTAURAR O SQL: \033[1;37m"
echo ""
echo -e "[1] - PAINEL WEB NO UBUNTU 18"
echo ""
echo -e "[2] - PAINEL WEB NO DEBIAN 8 OU UBUNTU 14"
echo ""
echo -ne "\033[1;36mOpção: \033[1;37m"
read resposta
if [[ "$resposta" = '1' ]]; then
    /bin/ppweb/restbanco18.sh
elif [[ "$resposta" = '2' ]]; then
/bin/ppweb/restbanco.sh
    else
 echo ""
    echo -e "\033[1;31mOpção inválida !\033[0m"
    sleep 1
    pweb
fi
}
painel_empresa () {
    /bin/ppweb/empresa.sh
}
#SENHA ROOT
senha_root () {
 /bin/ppweb/senharoot.sh
}
##PAINEL REMOVE
remove_painel () {
clear
echo -e "\033[1;32m SEMPRE CONFIRME COM \033[1;37mY"
echo -e "\033[1;32m PROSSIGA COM \033[1;37mENTER"
sleep 7
service apache2 stop
apt-get purge mysql-server mysql-client mysql-common mysql-server-core-* mysql-client-core-*
rm -rf /etc/mysql /var/lib/mysql
rm -rf /var/www/html
apt-get autoremove
apt-get autoclean
apt-get install apache2 -y &>/dev/null
sed -i "s;Listen 80;Listen 81;g" /etc/apache2/ports.conf
service apache2 restart > /dev/null 2>&1
service apache2 stop
[[ ! -d /var/www ]] && mkdir /var/www
[[ ! -d /var/www/html ]] && mkdir /var/www/html
echo -e "\033[1;36mPAINEL REMOVIDO COM ÊXITO \033[1;32m[!OK]"
pweb
}

##CLEAN HTML FOLDER
clean_htmlfolder () {
clear
echo -e "\E[41;1;37m         OTIMIZANDO A PASTA HTML PARA INSTALAÇÃO        \E[0m"
echo -e " "
echo -ne "\033[1;33m[\033[1;31m ! \033[1;33m] \033[1;31mATUALIZANDO"; fun_prog 'fun_update'
echo -e " "
echo -ne "\033[1;33m[\033[1;31m ! \033[1;33m] \033[1;31mOTIMIZANDO"; fun_prog 'fun_upgrade'
echo -e " "
echo -ne "\033[1;33m[\033[1;31m ! \033[1;33m] \033[1;31mLIMPANDO PASTA HTML"; fun_prog 'fun_limpiarepositorios'
echo -e " "
echo -ne "\033[1;33m[\033[1;31m ! \033[1;33m] \033[1;31mRETORNANDO"; fun_prog 'sleep 3'
sleep 1
echo -e " "
pweb
}
att_pweb () {
clear
echo -e "\E[41;1;37m         BAIXANDO ULTIMA VERSÃO        \E[0m"
echo -e " "
echo -ne "\033[1;33m[\033[1;31m ! \033[1;33m] \033[1;31mATUALIZANDO"; fun_prog 'fun_atpweb'
echo -e " "
echo -e " "
echo -ne "\033[1;33m[\033[1;31m ! \033[1;33m] \033[1;31mRETORNANDO"; fun_prog 'sleep 3'
sleep 5
echo -e " "
pweb
}

while true $x != "ok"
do
#
IP=$(wget -qO- ipv4.icanhazip.com)
echo "America/Sao_Paulo" > /etc/timezone
ln -fs /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime > /dev/null 2>&1
dpkg-reconfigure --frontend noninteractive tzdata > /dev/null 2>&1
clear
echo -e "\033[1;37m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\033[0m"
echo -e "\033[1;37m┃                       \033[38;5;118mPAINEL \033[38;5;190mGESTOR\033[38;5;197m-\033[38;5;164mSS\033[38;5;203mH\033[38;5;197m\033[1;37m                      ┃\E[0m"
echo -e "\033[1;37m┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫\033[0m"
echo -e "\033[1;37m┃\033[38;5;82mSISTEMA              \033[1;37m| \033[38;5;82mMEMÓRIA RAM           \033[1;37m| \033[38;5;82mPROCESSADOR    \033[1;37m┃"
echo -e "┃\033[38;5;196mOS: \033[1;37m$_system   | \033[38;5;196mTOTAL:\033[1;37m$_ram      | \033[38;5;196mNUCLEO: \033[1;37m$_core\033[0m  \033[1;37m┃"
echo -e "┃\033[38;5;196mHORÁRIO: \033[1;37m$_hora    | \033[38;5;196mEM USO: \033[1;37m$_usor      | \033[38;5;196mEM USO: \033[1;37m$_usop\033[0m  \033[1;37m┃"
echo -e "\033[1;37m┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫\033[0m"
echo -e "\033[1;37m┃\033[1;31m[\033[1;36m01\033[1;31m] \033[1;37m• \033[1;37mINSTALAR PAINEL SWIT-T         \033[1;32m                        \033[1;37m┃"
echo -e "┃\033[1;31m[\033[1;36m02\033[1;31m] \033[1;37m• \033[1;37mATUALIZAR PAINEL SWIT-T        \033[1;31m                        \033[1;37m┃"
echo -e "┃\033[1;31m[\033[1;36m03\033[1;31m] \033[1;37m• \033[1;37mALTERAR NOME DA LOGO \033[1;31m                                  \033[1;37m┃"
echo -e "┃\033[1;31m[\033[1;36m04\033[1;31m] \033[1;37m• \033[1;37mRESTAURAR BANCO DE DADOS \033[1;31m                              \033[1;37m┃"
echo -e "┃\033[1;31m[\033[1;36m05\033[1;31m] \033[1;37m• \033[1;37mLIMPAR A PASTA HTML \033[1;31m(cuidado!!!)                       \033[1;37m┃"
echo -e "┃\033[1;31m[\033[1;36m06\033[1;31m] \033[1;37m• \033[1;37mREMOVER PAINEL \033[1;31m                                        \033[1;37m┃"
echo -e "┃\033[1;31m[\033[1;36m07\033[1;31m] \033[1;37m• \033[1;37mBAIXAR ÚLTIMA VERSÃO DO PWEB \033[1;31m                          \033[1;37m┃"
echo -e "┃\033[1;31m[\033[1;36m08\033[1;31m] \033[1;37m• \033[1;37mMUDAR A SENHA ROOT \033[1;31m                                    \033[1;37m┃"
echo -e "┃\033[1;31m[\033[1;36m00\033[1;31m] \033[1;37m• \033[1;37mSAIR \033[1;32m<\033[1;33m<\033[1;31m<\033[0m \033[0m                                              \033[1;37m┃"
echo -e "\033[1;37m┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\033[0m"
echo -ne "\033[1;37m┗━┫\033[1;32mO QUE DESEJA FAZER \033[1;31m? : "; read -r x

case "$x" in 
   1 | 01)
   clear
   painel_inst
   exit;
   ;;
   2 | 02)
   clear
   painel_att
   exit;
   ;;
   3 | 03)
   clear
   painel_empresa
   exit;
   ;;
   4 | 04)
   clear
   painel_rest
   exit;
   ;;
   5 | 05)
   clear
   clean_htmlfolder
   exit;
   ;;
   6 | 06)
   clear
   remove_painel
   exit;
   ;;
   7 | 07)
   clear
   att_pweb
   exit;
   ;;
   8 | 08)
   clear
   senha_root
   exit;
   ;;
   0 | 00)
   echo -e "\033[1;31mSaindo...\033[0m"
   sleep 2
   clear
   exit;
   ;;
   *)
   echo -e "\n\033[1;31mOpção inválida !\033[0m"
   sleep 2
esac
done
#fim
